### ISSUE TITLE
Link sa home page ne radi

### ISSUE THREAD

**Issue by deancupovic** [fdzafic/SI2014Tim5#1]
Link na intervju ne radi sa stranice home page.

**Comment by fdzafic** [comment]
Eto sad radi. Naknadno sam na stranici intervjua promijenio slovo u title-u, pa se automatski i link promijenio, što nisam očekivao. Hvala na uočenoj greški.


lp






Od: Dean Cupovic
Poslano: ‎nedjelja‎, ‎22‎. ‎mart‎ ‎2015 ‎22‎:‎22
Prima: fdzafic/SI2014Tim5





Link na intervju ne radi sa stranice home page.
